; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = src

[env:src]
platform = espressif32@^6.3.2
board = esp32-s3-devkitc-1

framework = arduino
monitor_speed = 115200 
; debug_tool = esp-builtin
; upload_protocol = esp-builtin
upload_speed = 921600 
board_upload.flash_size = 16MB
board_build.f_cpu = 240000000L
board_build.flash_freq=80M
board_build.flash_mode = qio

board_build.arduino.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi

; Full symbolic debug information and no optimization
; build_type = debug
; Serial Monitor Decode esp32 Exception Stack ,Display Time ,Display Debug Information
; monitor_filters = esp32_exception_decoder, time, debug
build_flags = 
        -Wall ;all errors that everybody could agree on
        -Wextra ;somebody agree on
        -DCORE_DEBUG_LEVEL=1 ;Debug level 0-5
        -DBOARD_HAS_PSRAM ;Start Psram
        -DARDUINO_USB_MODE=1
        -DARDUINO_USB_CDC_ON_BOOT=1 ;1 is to use the USB port as a serial port
        -DARDUINO_RUNNING_CORE=1       ; Arduino Runs On Core (setup, loop)
        -DARDUINO_EVENT_RUNNING_CORE=1 ; Events Run On Core
lib_deps = bitbank2/AnimatedGIF@^2.2.0
