; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = src

[env:src]
platform = espressif32@^6.12.0
board = esp32s3-n16r16

framework = arduino
monitor_speed = 115200 
monitor_filters = esp32_exception_decoder
build_flags = 
        -Wall
        -Wextra 
        -Wno-unused-parameter
        -Wno-unused-variable

board_build.filesystem = littlefs

